version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python ml_script.py
      - docker build -t your-docker-image .
      - docker tag your-docker-image:latest your-docker-repo/your-docker-image:latest
      - $(aws ecr get-login --no-include-email --region your-region)
      - docker push your-docker-repo/your-docker-image:latest
artifacts:
  files:
    - '**/*'
